name: nextjs

on:
  push:
    branches:
      - main

jobs:
  lintTest:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          echo "Running Installing Dependencies ..."
          npm install

      - name: Run Linting
        run: |
          echo "Running Linting test ..."
          npm run lint
        env:
          CI: true

  SecurityCheck:
    name: Check for Security
    runs-on: ubuntu-latest
    steps:
      - name: Check for Security
        run: |
          echo "Running Security Checks.."
          sleep 5s
          echo "Running Security Checks.. 1"
          sleep 5s
          echo "Running Security Checks.. 2"
          sleep 5s
          echo "Running Security Checks.. 3"
          sleep 5s
  Deploy:
    name: Deployment 
    runs-on: ubuntu-latest
    needs: [lintTest, SecurityCheck]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        working-directory: ./tutcicd
        run: |
          echo "Deployment in Progress ..."
          npm install

      # Add other deployment steps as needed
      - name: Build with Next.js
        working-directory: ./tutcicd
        run: npm run build

      - name: Deploy to Server
        working-directory: ./tutcicd
        run: |
          echo "Deploying to the server..."
          # Add your deployment steps here
